In [1]:
import numpy as np

# 行列Aの定義 (3x2)
A = np.array([
    [0, 1],
    [2, 3],
    [4, 5]
])

# 行列Bの定義 (2x4)
B = np.array([
    [0, 1, 2, 3],
    [4, 5, 6, 7]
])

# 行列の積を計算 (3x2) ・ (2x4) => (3x4)
# np.dot(A, B) または A @ B で計算可能です
product_matrix = A @ B

# 結果の表示
print("行列の積:")
print(product_matrix)

# 行列内の要素の最大値を計算
max_value = np.max(product_matrix)

print(f"\n行列内の最大値: {max_value}")

行列の積:
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]

行列内の最大値: 47
